# Generated by Django 5.1.1 on 2024-10-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경일')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('content', models.TextField(verbose_name='내용')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('dislikes', models.IntegerField(default=0, verbose_name='싫어요 수')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='상태')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
