# Generated by Django 5.1.1 on 2024-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
    ]
