# Generated by Django 5.1.1 on 2024-10-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonWebToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경일')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('access_token', models.CharField(max_length=255, verbose_name='액세스 토큰')),
                ('access_expired_at', models.DateTimeField(verbose_name='액세스 토큰 만료일')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='리프레시 토큰')),
                ('refresh_expired_at', models.DateTimeField(verbose_name='리프레시 토큰 만료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_token', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
