# Generated by Django 5.1.1 on 2024-10-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonwebtoken',
            old_name='access_expired_at',
            new_name='access_expires_at',
        ),
        migrations.RenameField(
            model_name='jsonwebtoken',
            old_name='refresh_expired_at',
            new_name='refresh_expires_at',
        ),
    ]
